import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";




export const metadata = {
  title: "Tony Querrec - Photographe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={"py-[48px] px-[24px] md:px-[48px]"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
